### PR TITLE
Misc: remove double render, remove rack-charset middleware 

### LINKED ISSUE #13: Form submission is broken
The form on the `/show/data` page renders fine, but when I submit it I see this error in the browser:

```
Puma caught this error: Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return". (AbstractController::DoubleRenderError)
/Users/tom/.gem/ruby/2.7.2/gems/actionpack-6.1.3/lib/action_controller/metal/rendering.rb:35:in `render'
```

This started happening after #10 was merged.

### LINKED ISSUE #14: Rack::Charset middleware is unnecessary
Responses appear to have `charset=utf-8` in their `Content-Type` even when the `Rack::Charset` middleware is removed:

```
% git diff
diff --git a/mirth.rb b/mirth.rb
index 71d01fb..fff2d9d 100644
--- a/mirth.rb
+++ b/mirth.rb
@@ -36,5 +36,5 @@ def add_data
   match '*path', via: :all, to: DailyDataController.action(:all_paths)
 end 
 
-app_with_charset = Rack::Charset.new(router, 'utf-8')
+app_with_charset = router
 Rack::Handler::Puma.run(app_with_charset, :Port => 1234, :Verbose => true)

% ruby mirth.rb > /dev/null &

% curl --verbose http://0.0.0.0:1234/my/cool/path
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 1234 (#0)
> GET /my/cool/path HTTP/1.1
> Host: 0.0.0.0:1234
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Vary: Accept
< Transfer-Encoding: chunked
< 
* Connection #0 to host 0.0.0.0 left intact
✅ Received a GET request to /my/cool/path!
```

This started happening after #10 was merged.

### PR DESCRIPTION
**Pull request by wildmaples**
Fix: https://github.com/wildmaples/mirth/issues/14 and fix: https://github.com/wildmaples/mirth/issues/13

### CODE REVIEW

File: mirth.rb [hunk 1]
```diff
@@ -23,8 +23,7 @@ def show_data
 
   def add_data
     DailyData.create(date: params['date'], step_count: params["step_count"], notes: params["notes"])
-    redirect_to("/show/data")
-    render(status: :see_other)
+    redirect_to("/show/data", status: 303)
```
Comment (tomstuart) [inline mirth.rb:24]: This is what you had before, but I was [trying to say](https://github.com/wildmaples/mirth/pull/10#discussion_r581303492) that you can use `:see_other` instead of `303`.

File: mirth.rb [hunk 2]
```diff
@@ -35,5 +33,4 @@ def add_data
   match '*path', via: :all, to: DailyDataController.action(:all_paths)
 end 
 
-app_with_charset = Rack::Charset.new(router, 'utf-8')
-Rack::Handler::Puma.run(app_with_charset, :Port => 1234, :Verbose => true)
+Rack::Handler::Puma.run(router, :Port => 1234, :Verbose => true)
```
Comment (tomstuart) [inline mirth.rb:36]: Perfect!

**Review by tomstuart — APPROVED** [review]
Thank you for fixing both my issues. The customer service from MirthCorp is excellent 🙏🏻

File: mirth.rb (hunk 1 above)
Comment (wildmaples) [reply mirth.rb:24]: [LOL](https://github.com/wildmaples/mirth/pull/10#discussion_r581368734) but thanks, I get it now
